name: publish to nuget

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
      
      - name: Build
        run: dotnet pack ./osu.Framework.Live2D/osu.Framework.Live2D.csproj -c Release -o output

      - name: Publish
        run: dotnet nuget push ./output/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate --no-symbols true