name: publish to nuget

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        uses: actions/setup-dotnet@main
        with:
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      
      - name: Build
        run: ./deploy.ps1
        shell: pwsh

      - name: Publish to NuGet
        run: dotnet nuget push ./output/*.nupkg -k ${{secrets.NUGET_API_KEY}} --skip-duplicate --no-symbols true


      - name: Prepare Uploading for GitHub Registry
        uses: actions/setup-dotnet@main
        with:
          source-url: https://nuget.pkg.github.com/${{github.actor}}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{github.token}}

      - name: Publish to GitHub Package Registry
        run: dotnet nuget push ./output/*.nupkg --api-key ${{github.token}} --skip-duplicate --no-symbols true