name: publish to nuget

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: publish
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      
      - name: Build and Publish
        run: ./deploy.ps1
        shell: powershell
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

      - name: Prepare Uploading for GitHub Registry
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/vignette-project/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build and Publish
        run: ./deploy.ps1
        shell: powershell
        env:
          NUGET_API_KEY: ${{secrets.GITHUB_TOKEN}}