name: publish to nuget

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        uses: actions/setup-dotnet@main
        with:
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      
      - name: Build
        run: ./deploy.ps1
        shell: pwsh

      - name: Publish to NuGet
        run:  |
           dotnet nuget push ./output/*.nupkg -k ${{secrets.NUGET_API_KEY}} --skip-duplicate --no-symbols true && \
           dotnet tool install gpr -g && \
           gpr push ./output/*.nupkg --repository --repository https://github.com/vignette-project/osu-framework-live2d -k ${{github.token}}